name: hris156 regular exam CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 21.x
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
        cache: 'npm'
    - name: Install NPM dependencies
      run: npm install
    - name: Start
      run: npm run start &
    - name: Run the unit tests
      run: npm run test:unit
    - name: Display softuni username
      run: echo "hris156"

  run_ui_tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 21.x
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
        cache: 'npm'
    - name: Install NPM dependencies
      run: npm install
    - name: Install Playwright
      run: npx playwright install
    - name: Start the app
      run: npm run start &
    - name: Run the UI tests
      run: npm run test:ui